package_rename_config:
  android:
    app_name: Harsh WhatsApp
    package_name: com.harsh.whatsapp # (String) The package name of the android app
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

#  ios:
#    app_name: MySipOnline # (String) The display name of the ios app
#    bundle_name: # (String) The bundle name of the ios app
#    package_name: com.mysiponline.ios # (String) The product bundle identifier of the ios app
